import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
{/*}        className={`${geistSans.variable} ${geistMono.variable} antialiased`}*/}

      </head>
      <body
      >
        {children}
      </body>
    </html>
  );
}
